force failure in compile step

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -15,11 +15,7 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
-      - name: Force Failure
-        run: |
-          echo "This step will intentionally fail."
-          exit 1
+      
       - name: Cache SUT
         id: cache-sut
         uses: actions/cache@v4
@@ -79,6 +75,12 @@ jobs:
         env:
           http_proxy: ""
           https_proxy: ""
+      
+      - name: Force Failure
+        run: |
+          echo "This step will intentionally fail."
+          exit 1
+          
       - name: Compile simulation
         run: |
             environment-make -o ./environment-make -A Win32 ./environment-make/venvironment.yaml;
